Repository Ragnacodes/Legato-Backend, pull requests merged in 2021-06, with the labels that each got.

#66 Feature/v0.5/sse log
  api/logger.go
  api/scenario.go
  api/webhook.go
  cmd/legato_server/main.go
  db/dbmain.go
  db/discord.go
  db/http.go
  db/logs.go
  db/scenario.go
  db/service.go
  db/spotify.go
  db/telegram.go
  db/webhook.go
  docs/README.md
  docs/api/logs.md
  domain/logger.go
  domain/webhook.go
  go.mod
  go.sum
  helper/converter/logs.go
  helper/converter/webhook.go
  logging/stream.go
  logging/usecase/logging_usecase.go
  router/logging.go
  router/router.go
  router/webhook.go
  services/webhook/webhook_usecase.go
Labels: feature

#82 Fix/v0.6/redirect
  env/env.go
  router/auth_service.go
Labels: bug

#83 Fix/v0.6/minor dev issues
  db/http.go
  db/spotify.go
  db/ssh.go
  db/toolbox.go
  db/webhook.go
  helper/converter/connection.go
Labels: enhancement
