Repository Ragnacodes/Legato-Backend, pull requests merged in 2021-05, with the labels that each got.

#35 Fix/v0.3/digest nodes
  db/scenario.go
  scenario/usecase/scenario_usercase.go
Labels: bug, enhancement

#33 Feature/v0.3/spotify
  .github/workflows/ci.yml
  api/spotify.go
  db/dbmain.go
  db/service.go
  db/spotify.go
  db/telegram.go
  db/webhook.go
  deployments/dev/web.env.sample
  docker-compose-dev.yml
  docs/api/spotify.md
  domain/spotify.go
  domain/webhook.go
  env/.env.sample
  env/env.go
  go.mod
  go.sum
  helper/converter/spotify.go
  main.go
  router/node.go
  router/router.go
  router/spotify.go
  router/webhook.go
  services/spotify/spotify_usecase.go
  services/webhook/webhook_usecase.go
Labels: documentation, feature

#14 Feature/v0.1/authentication test
  authenticate/auth_test.go
  go.mod
  go.sum
Labels: enhancement

#58 Scheduling and threading enhancements
  api/scenario.go
  api/scheduler.go
  authenticate/auth_test.go
  cmd/legato_scheduler/main.go
  cmd/legato_server/main.go
  db/scenario.go
  docker-compose-dev.yml
  docs/api/scenario.md
  domain/scenario.go
  env/.env.sample
  env/env.go
  go.mod
  go.sum
  helper/converter/scenarios.go
  router/initial_routes.go
  router/scenario.go
  scenario/usecase/scenario_usercase.go
  scheduler/router.go
  scheduler/routes.go
  scheduler/runner.go
  scheduler/task_manager.go
  scheduler/tasks.go
Labels: documentation, enhancement, feature

#59 Feature/v0.4/ssh
  api/ssh.go
  api/user.go
  cmd/legato_server/main.go
  db/connection.go
  db/dbmain.go
  db/service.go
  db/ssh.go
  docs/api/connection.md
  docs/api/service.md
  docs/api/ssh.md
  domain/ssh.go
  domain/user.go
  helper/converter/ssh.go
  router/auth_service.go
  router/node.go
  router/router.go
  router/ssh.go
  services/ssh/ssh_usecase.go
  user/usecase/user_usecase.go
Labels: documentation, feature
